### ISSUE TITLE
Support re-usable workflows

### ISSUE THREAD

**Issue by hendrikmaus** [hendrikmaus/actions-digest#18]
For example:

```yaml
jobs:
  rust-workflows-ci:
    name: CI
    uses: hendrikmaus/rust-workflows/.github/workflows/ci.yaml@v0.8.0
```
